/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as PomodoroRouteImport } from './routes/pomodoro'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesSubjectRouteImport } from './routes/games.$subject'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const PomodoroRoute = PomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSubjectRoute = GamesSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => GamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/flashcards': typeof FlashcardsRoute
  '/games': typeof GamesRouteWithChildren
  '/notes': typeof NotesRoute
  '/pomodoro': typeof PomodoroRoute
  '/tasks': typeof TasksRoute
  '/games/$subject': typeof GamesSubjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/flashcards': typeof FlashcardsRoute
  '/games': typeof GamesRouteWithChildren
  '/notes': typeof NotesRoute
  '/pomodoro': typeof PomodoroRoute
  '/tasks': typeof TasksRoute
  '/games/$subject': typeof GamesSubjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/flashcards': typeof FlashcardsRoute
  '/games': typeof GamesRouteWithChildren
  '/notes': typeof NotesRoute
  '/pomodoro': typeof PomodoroRoute
  '/tasks': typeof TasksRoute
  '/games/$subject': typeof GamesSubjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/flashcards'
    | '/games'
    | '/notes'
    | '/pomodoro'
    | '/tasks'
    | '/games/$subject'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/flashcards'
    | '/games'
    | '/notes'
    | '/pomodoro'
    | '/tasks'
    | '/games/$subject'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/flashcards'
    | '/games'
    | '/notes'
    | '/pomodoro'
    | '/tasks'
    | '/games/$subject'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FlashcardsRoute: typeof FlashcardsRoute
  GamesRoute: typeof GamesRouteWithChildren
  NotesRoute: typeof NotesRoute
  PomodoroRoute: typeof PomodoroRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pomodoro': {
      id: '/pomodoro'
      path: '/pomodoro'
      fullPath: '/pomodoro'
      preLoaderRoute: typeof PomodoroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$subject': {
      id: '/games/$subject'
      path: '/$subject'
      fullPath: '/games/$subject'
      preLoaderRoute: typeof GamesSubjectRouteImport
      parentRoute: typeof GamesRoute
    }
  }
}

interface GamesRouteChildren {
  GamesSubjectRoute: typeof GamesSubjectRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesSubjectRoute: GamesSubjectRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FlashcardsRoute: FlashcardsRoute,
  GamesRoute: GamesRouteWithChildren,
  NotesRoute: NotesRoute,
  PomodoroRoute: PomodoroRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
